# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        url: jdbc:mysql://localhost:3306/Proyecto?useUnicode=true&characterEncoding=utf8&useSSL=false
        name: proyecto
        username: root
        password: aus2011
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    mail:
        host: smtp.gmail.com
        port: 587
        username: applicationserverinfo@gmail.com   # glanati - 25/07/16: setting up mail for new accounts
        password: system1234
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
    profiles:
        include: swagger # automatically set the 'swagger' profile

liquibase:
    contexts: dev

server:
    port: 8080

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 16M
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: 18aa83736cb2c6b9e3f820cd402d6b0558cfb3d2
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: Proyecto@localhost
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: Proyecto
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
